### ISSUE TITLE
-e (--eu) CLI flag doesn't seem to work

### ISSUE THREAD

**Issue by devilleweppenaar** [ovhemert/pino-datadog#25]
When including the `-e` (or `--eu`) CLI flag I get a status 403:

```
> node --unhandled-rejections=strict --optimize_for_size --max_old_space_size=115 --gc_interval=100 . | pino-datadog

{"level":30,"time":1574122975941,"pid":91734,"hostname":"[redacted]","msg":"App is running under env 'development', listening on port 8080, and has an available heap size of 113303784 bytes (~0.11GB)","v":1}
The previous log have not been saved
Request failed with status code 403
Error: Request failed with status code 403
    at createError (/Users/devillexio/Developer/devillexio/pino-datadog/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/devillexio/Developer/devillexio/pino-datadog/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/devillexio/Developer/devillexio/pino-datadog/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

The same config works when I exclude the flag.

**Comment by ovhemert** [comment]
I think this is caused by the region that is assigned to your DataDog account.
When you've signed up and your account is in the US region, it might not be possible to use the EU endpoints to send logs and vice versa.

**Comment by devilleweppenaar** [comment]
That's interesting. I think you are right. Do you know of a way to check which region a Datadog account is?

**Comment by ovhemert** [comment]
Searched a bit more... for the API it notes the difference here: 
https://docs.datadoghq.com/api/?lang=python#api-reference

Not sure where to find it in the account settings. If it's an account that already exists for a long time, you will be in US region since Europe (Germany) came later.

**Comment by devilleweppenaar** [comment]
Ah, that makes a lot of sense. Thanks for your effort!
